local Config = {
    title = "Majic Blue Mechanics",
    baseWidth = 960,
    baseHeight = 678,
    player = {
        character = "mechanic-raccoon",
        spawnX = 520,
        spawnY = 480,
        speed = 155,
        maxWidth = 132,
        maxHeight = 112,
    },
    characterRendering = {
        -- Match Picture Shop's visible-frame normalization. Every action is
        -- measured against the same source height before fitting the shop.
        referenceHeight = 256,
    },
    businessCalendar = { secondsPerDay = 300 },
    customer = {
        characterPool = { "business-dragon", "business-fox", "business-cat" },
        maxWidth = 132,
        maxHeight = 112,
        speed = 72,
        walkAnimationRate = 4,
        initialArrivalDelayMin = 2,
        initialArrivalDelayMax = 6,
        arrivalDelayMin = 60,
        arrivalDelayMax = 150,
        maxWaitSeconds = 300,
        interactionRadius = 58,
        route = {
            { x = 645, y = 235 },
            { x = 650, y = 245 },
            { x = 640, y = 270 },
            { x = 630, y = 295 },
            { x = 635, y = 320 },
            { x = 650, y = 340 },
            { x = 680, y = 350 },
            { x = 720, y = 355 },
            { x = 760, y = 360 },
        },
        seatSpots = {
            { name = "left-chair", x = 725, y = 320, facing = 1 },
            { name = "couch", x = 812, y = 320, facing = -1 },
            { name = "right-chair", x = 894, y = 390, facing = -1 },
        },
    },
    interactables = {
        computer = { x = 500, y = 185, radius = 62 },
        -- The regenerated shop has two service lifts. The left lift is the
        -- starter bay and is kept on the original walkmask's floor area.
        serviceBay = { x = 300, y = 336, radius = 86 },
    },
    loadingBay = {
        sourceX = 200,
        sourceY = 170,
        frameWidth = 260,
        frameHeight = 260,
        frameCount = 5,
        duration = 0.9,
        interaction = { x = 300, y = 285, radius = 62 },
        obstacle = { x = 215, y = 267, radius = 55 },
    },
    partsDelivery = {
        frameSize = 512,
        cargoFrameCount = 5,
        scheduleDelay = 2.5,
        backingDuration = 2.2,
        cargoDuration = 0.75,
        maximumOrders = 5,
        bodyAxis = { x = 1, y = 0.42 },
        start = { x = -150, y = 232, scale = 0.94 },
        parked = { x = 54, y = 318, scale = 0.94 },
        rearOpeningOffsetX = 160,
        interaction = { x = 218, y = 310, radius = 58 },
        obstacle = { offsetX = 0, offsetY = -8, radius = 72 },
        aperture = {
            { x = 138, y = 149 }, { x = 270, y = 124 },
            { x = 270, y = 247 }, { x = 138, y = 273 },
        },
    },
    motorcycleTransport = {
        scheduleDelay = 2.5,
        backingDuration = 2.2,
        ownerPickupDelay = 3.5,
        frameWidth = 1402,
        frameHeight = 1122,
        -- The flatbed is intentionally 20% smaller than its original dock
        -- presentation.  Moving the anchor right keeps its deck aligned with
        -- the loading-bay threshold after scaling around the truck's center.
        start = { x = -117, y = 210, scale = 0.272 },
        parked = { x = 87, y = 296, scale = 0.272 },
        -- Transport bikes sit toward the exposed rear half of the deck, not
        -- up against the cab hidden behind the doorway.
        bikeOffsetX = 280,
        bikeOffsetY = -60,
        -- These source-space bounds compensate for the smaller parent truck,
        -- yielding a motorcycle that is 40% larger on screen than before.
        bikeMaxWidth = 613,
        bikeMaxHeight = 429,
        interaction = { x = 218, y = 270, radius = 68 },
        obstacle = { offsetX = 0, offsetY = -8, radius = 78 },
        aperture = {
            { x = 138, y = 149 }, { x = 270, y = 124 },
            { x = 270, y = 247 }, { x = 138, y = 273 },
        },
    },
    serviceBay = {
        bikeX = 300,
        bikeY = 336,
        bikeScale = 0.72,
        collisionHalfWidth = 74,
        collisionHalfHeight = 20,
    },
    roadTest = {
        courseLength = 42000,
        departureLength = 3600,
        arrivalLength = 3600,
        garageSourceHorizonY = 350,
        garageScreenHorizonY = 320,
        garageBlendDistance = 500,
        cameraMinimumSpeed = 260,
        cameraRiderDepthBase = 0.22,
        cameraRiderDepthRange = 0.40,
        depthResponse = 3.2,
        bikeY = 565,
        roadWidth = 430,
        maxSpeed = 1680,
        speedDisplayScale = 0.10,
        acceleration = 960,
        sprintMultiplier = 1.5,
        scrollSpeedScale = 0.55,
        braking = 540,
        coasting = 92,
        steering = 0.78,
        maxLean = 0.11,
        leanResponse = 12,
        cameraResponse = 5.0,
        traffic = {
            startDistance = 5200,
            spacing = 2600,
            spacingJitter = 520,
            collisionDistance = 210,
            collisionLaneWidth = 0.28,
            collisionSlowdown = 0.42,
            laneHalfWidth = 177,
            nearWidth = 178,
            farWidth = 12,
            spriteScale = 1.20,
            hitCooldown = 0.85,
        },
        runner = {
            centerX = 480,
            horizonY = 250,
            horizonSourceY = 405,
            bottomY = 710,
            nearClip = 105,
            farClip = 2600,
            farHalfWidth = 24,
            nearHalfWidth = 590,
            roadSlices = 120,
            roadTextureWorldLength = 760,
            centerDashPeriod = 600,
            centerDashLength = 230,
            centerLineHalfWidthRatio = 0.012,
            edgeLinePositionRatio = 0.84,
            edgeLineHalfWidthRatio = 0.009,
            sectionLength = 1800,
            sectionSlices = 256,
            sectionRoadEdgeRatio = 0.92,
            leftSectionNearHeight = 610,
            rightSectionNearHeight = 540,
            leftSectionVTop = 0.024,
            leftSectionVBottom = 1.0,
            rightSectionVTop = 0.155,
            rightSectionVBottom = 0.810,
            citySourceGroundY = 990,
            cityScreenGroundY = 274,
            graffitiNearWidth = 118,
            graffitiFarWidth = 10,
            graffitiMinimumAmount = 0.12,
            graffitiWallInset = 260,
        },
    },
    paths = {
        workshop = "assets/workshop/workshop-layout-v2.png",
        walkmask = "assets/workshop/workshop-walkmask.png",
        deliveryTruck = "assets/delivery/delivery-truck-open.png",
        motorcycleFlatbed = "assets/delivery/motorcycle-flatbed-empty.png",
        truckCargoDoor = "assets/delivery/truck-cargo-door-strip.png",
        loadingBayDoor = "assets/delivery/loading-bay-door-strip.png",
        motorcycleSide = "assets/motorcycles/gsxr-600-service.png",
        motorcyclePoster = "assets/motorcycles/gsxr-600-poster.png",
        motorcycleAction = "assets/motorcycles/gsxr-600-action.png",
        repairParts = {
            oil = "assets/repair-parts/oil.png",
            brake = "assets/repair-parts/brake.png",
            chain = "assets/repair-parts/chain.png",
            stator = "assets/repair-parts/stator.png",
            suspension = "assets/repair-parts/suspension.png",
            belt = "assets/repair-parts/belt.png",
            spoke = "assets/repair-parts/spoke.png",
            carb = "assets/repair-parts/carb.png",
            magneto = "assets/repair-parts/magneto.png",
            coolant = "assets/repair-parts/coolant.png",
        },
        repairTools = {
            ratchet = "assets/repair-tools/ratchet.png",
            spanner = "assets/repair-tools/spanner.png",
            screwdriver = "assets/repair-tools/screwdriver.png",
            filterWrench = "assets/repair-tools/filter-wrench.png",
            funnel = "assets/repair-tools/funnel.png",
        },
        diagnosticReader = {
            "assets/tools/diagnostic-reader-frame-01.png",
            "assets/tools/diagnostic-reader-frame-02.png",
            "assets/tools/diagnostic-reader-frame-03.png",
            "assets/tools/diagnostic-reader-frame-04.png",
        },
        motorcycles = {
            nakedBlack = {
                service = "assets/motorcycles/naked-black-service.png",
                mounted = "assets/motorcycles/naked-black-mounted.png",
                transport = "assets/motorcycles/naked-black-transport.png",
                rear = "assets/motorcycles/naked-black-rear.png",
            },
            vintageRedStandard = {
                service = "assets/motorcycles/vintage-red-standard-service.png",
                mounted = "assets/motorcycles/vintage-red-standard-mounted.png",
                transport = "assets/motorcycles/vintage-red-standard-transport.png",
                rear = "assets/motorcycles/vintage-red-standard-rear.png",
            },
            blackClassic = {
                service = "assets/motorcycles/black-classic-service.png",
                mounted = "assets/motorcycles/black-classic-mounted.png",
                transport = "assets/motorcycles/black-classic-transport.png",
                rear = "assets/motorcycles/black-classic-rear.png",
            },
            redSupersport = {
                service = "assets/motorcycles/red-supersport-service.png",
                mounted = "assets/motorcycles/red-supersport-mounted.png",
                transport = "assets/motorcycles/red-supersport-transport.png",
                rear = "assets/motorcycles/red-supersport-rear.png",
            },
            adventureSilverRed = {
                service = "assets/motorcycles/adventure-silver-red-service.png",
                mounted = "assets/motorcycles/adventure-silver-red-mounted.png",
                transport = "assets/motorcycles/adventure-silver-red-transport.png",
                rear = "assets/motorcycles/adventure-silver-red-rear.png",
            },
            redVtwinCruiser = {
                service = "assets/motorcycles/red-vtwin-cruiser-service.png",
                mounted = "assets/motorcycles/red-vtwin-cruiser-mounted.png",
                transport = "assets/motorcycles/red-vtwin-cruiser-transport.png",
                rear = "assets/motorcycles/red-vtwin-cruiser-rear.png",
            },
            adventureBlueWhite = {
                service = "assets/motorcycles/adventure-blue-white-service.png",
                mounted = "assets/motorcycles/adventure-blue-white-mounted.png",
                transport = "assets/motorcycles/adventure-blue-white-transport.png",
                rear = "assets/motorcycles/adventure-blue-white-rear.png",
            },
            uralTanClassic = {
                service = "assets/motorcycles/ural-tan-classic-service.png",
                mounted = "assets/motorcycles/ural-tan-classic-mounted.png",
                transport = "assets/motorcycles/ural-tan-classic-transport.png",
                rear = "assets/motorcycles/ural-tan-classic-rear.png",
            },
            bmwR24Vintage = {
                service = "assets/motorcycles/bmw-r24-vintage-service.png",
                mounted = "assets/motorcycles/bmw-r24-vintage-mounted.png",
                transport = "assets/motorcycles/bmw-r24-vintage-transport.png",
                rear = "assets/motorcycles/bmw-r24-vintage-rear.png",
            },
            modernGrayCruiser = {
                service = "assets/motorcycles/modern-gray-cruiser-service.png",
                mounted = "assets/motorcycles/modern-gray-cruiser-mounted.png",
                transport = "assets/motorcycles/modern-gray-cruiser-transport.png",
                rear = "assets/motorcycles/modern-gray-cruiser-rear.png",
            },
        },
        roadTest = {
            background = "assets/road-test/parking-lot-option-a.png",
            runnerHorizon = "assets/road-test/runner-sky.png",
            runnerRoad = "assets/road-test/runner-road-texture.png",
            runnerCity = "assets/road-test/runner-city-horizon.png",
            runnerLeftSection = "assets/road-test/runner-left-wall-texture-long.png",
            runnerRightSection = "assets/road-test/runner-right-wall-texture-long.png",
            runnerGraffiti = {
                "assets/road-test/runner-graffiti-raccoon.png",
                "assets/road-test/runner-graffiti-fox.png",
                "assets/road-test/runner-graffiti-owl.png",
                "assets/road-test/runner-graffiti-snake.png",
                "assets/road-test/runner-graffiti-wrench.png",
                "assets/road-test/runner-graffiti-ride.png",
                "assets/road-test/runner-graffiti-shift.png",
                "assets/road-test/runner-graffiti-majic.png",
            },
            traffic = {
                "assets/road-test/traffic/traffic-hatchback-teal.png",
                "assets/road-test/traffic/traffic-sedan-orange.png",
                "assets/road-test/traffic/traffic-van-blue.png",
                "assets/road-test/traffic/traffic-pickup-olive.png",
            },
            riderHit = {
                "assets/road-test/rider-hit/frame-01.png",
                "assets/road-test/rider-hit/frame-02.png",
                "assets/road-test/rider-hit/frame-03.png",
                "assets/road-test/rider-hit/frame-04.png",
            },
            rider = "assets/road-test/mechanic-raccoon-rider.png",
        },
    },
    characters = {
        ["mechanic-raccoon"] = {
            idle = "assets/characters/mechanic-raccoon/idle.png",
            walk = "assets/characters/mechanic-raccoon/walk.png",
            use = "assets/characters/mechanic-raccoon/use.png",
        },
        ["business-dragon"] = {
            idle = "assets/characters/business-dragon/idle.png",
            walk = "assets/characters/business-dragon/walk.png",
            sit = "assets/characters/business-dragon/sit.png",
        },
        ["business-fox"] = {
            idle = "assets/characters/business-fox/idle.png",
            walk = "assets/characters/business-fox/walk.png",
            sit = "assets/characters/business-fox/sit.png",
        },
        ["business-cat"] = {
            idle = "assets/characters/business-cat/idle.png",
            walk = "assets/characters/business-cat/walk.png",
            sit = "assets/characters/business-cat/sit.png",
        },
    },
}

return Config
